development: &default
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  reaping_frequency: <%= ENV.fetch("DB_REAPING_FREQUENCY", 10) %>
  timeout: 5000
  url: <%= ENV.fetch("DATABASE_URL", "") %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "") + "_test" %>

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [ENV.fetch("RAILS_MAX_THREADS", 5), ENV.fetch("DB_POOL", 5)].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>
