# frozen_string_literal: true
source "https://rubygems.org"

ruby "2.4.1"

gem "dry-validation"
gem "jwt"
gem "lograge"
gem "pg"
gem "puma"
gem "rack-cors"
gem "rails", "~> 5.1"
gem "rails-i18n", "~> 5.0.0"

group :development, :test do
  gem "awesome_print"
  gem "bundler-audit", require: false
  gem "dotenv-rails"
  gem "fabrication"
  gem "faker"
  gem "pry-byebug"
  gem "pry-rails"
  gem "rswag"
end

group :development do
  gem "better_errors"
  gem "binding_of_caller" # Enables the REPL in better errors console
  gem "guard-ctags-bundler"
  gem "guard-rspec"
  gem "listen"
  gem "rubocop"
  gem "rubocop-github"
end

group :test do
  gem "database_cleaner"
  gem "rspec-prof"
  gem "rspec-rails"
  gem "ruby-prof"
  gem "timecop"
  gem "webmock"
end

group :production do
  gem "bugsnag"
  gem "newrelic_rpm"
  gem "rack-timeout"
  gem "rails_12factor"
end
